### ISSUE TITLE
I respect your work.

### ISSUE THREAD

**Issue by selon14** [IMarkoMC/Tokens#101]
I found my token here. It wasnt an important token and i usually do hide important tokens. But i remember when i was a begginer and didnt know i needed to hide my tokens. This is a good way of teaching people to hide them. Keep doing what you're doing. Im sure many begginers are learning a lot.

Thank you!

**Comment by skidmaster69420** [comment]
Hello there,

Thank you for thanking us, so that we can thank you for thanking us, so that we can thank the thanking that has occured by thanking you and thanking us.....

This is probably not how that goes... I will be fired for messing this up, but the goverment pays me shit anyways!
Fuck the Government! Fuck the American People! Fuck the Legal System!

Yours,
Unpaid FBI Fly Agent

>**Note**

The Agent that wrote this post has been arrested and is awaiting trial. 
The Agent is assumed to have suffered severe brain damage.
Which seems to have been a result by them trying to understand the posts that this account posted.
Our thoughts are with the Agent.
However, they will never be paid.

Flying, Bullshittery, Intellectually.
Fly Bureau of Investigation.
