### ISSUE TITLE
Thanks bro

### ISSUE THREAD

**Issue by DEez78** [IMarkoMC/Tokens#118]
Thank you so much, bro.

**Comment by skidmaster69420** [comment]
You're welcome, broski. (is that nerd still lit with the kids).

P.S. The fly is still just flying around in my room. And the spider is just sitting there. Rent-free. Well guess what? The lease is up next month buddy, and you're getting evicted! As the fly, you're doing in this glass buddy. If you opt to go into the glass now, I'll take you outside. Peacefully. Otherwise, I will START A WAR with you. You fucking fly, flying around my damn room.
