### ISSUE TITLE
Fuck off 

### ISSUE THREAD

**Issue by e6** [IMarkoMC/Tokens#133]
Loser skid go do something with your life

**Comment by Whanos** [comment]
LMAOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by IMarkoMC** [comment]
![don't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're a (insert stereotype) + not funny didn't laugh + you're* + grammar issue + go outside + get good + reported + ad hominem + GG! + ur mom](https://media.tenor.com/fGAe4omlBhUAAAAC/cope-harder.gif)

**Comment by skidmaster69420** [comment]
esix? Who do you think you are-- the robotic cat with a fiery tail? Will you also be educating me with the 12 funny and EXCITED new things I could be doing with a cheesegreater? No, because you will never live up the expectations of my waifu, esix. Esix would never called me a looser enough I didn't tag my shit correctly. Even hexerade would of been okay. But, you're just upset that you didn't protect your discord token like all the obtuse GitHub users that we see here. You disappoint me and every other furry that might exist on the internet that you are slandering esix and using up a very good GitHub username.

Please purchase soup.

Reginald Homo
Degenerate Fly 
skidmaster69420
