### ISSUE TITLE
i have a large cock

### ISSUE THREAD

**Issue by MRfiesta1** [IMarkoMC/Tokens#136]
FUCK YOU YA PRICK!

**Comment by Die-Antwoord** [comment]
> FUCK YOU YA PRICK!

lol skid mad

**Comment by IMarkoMC** [comment]
![don't care + didn't ask + cry about it + stay mad + get real + L + mald seethe cope harder + hoes mad + basic + skill issue + ratio + you fell off + the audacity + triggered + any askers + redpilled + get a life + ok and? + cringe + touch grass + donowalled + not based + your're a (insert stereotype) + not funny didn't laugh + you're* + grammar issue + go outside + get good + reported + ad hominem + GG! + ur mom](https://media.tenor.com/fGAe4omlBhUAAAAC/cope-harder.gif)

**Comment by skidmaster69420** [comment]
Dear Mr. Fiesta the First,

We recently received your order for 1 extra small condom. Unfortunately, we will be unable to fulfill your shipment due to a series of freak fulfillment accidents. Firstly, a group of children broke into the warehouse and used all the condoms as water balloons, and they had a "sick ass" water balloon fight. Secondly, once we obtained additional stock, a man with a bulldozer drove into the warehouse and destroyed the racking. Finally, a fucking meteor hit the warehouse and set it on turbo fire.

Due to these reasons, we will be returning the iHOP gift card you sent us as payment for your order.

Quiftohper Lesbiana
FlyEx Shipment Service
SKIDMASTER69420 LLC
