### ISSUE TITLE
cumm was on github?

### ISSUE THREAD

**Issue by bl-d** [IMarkoMC/Tokens#14]
cummmm?

**Comment by skidmaster69420** [comment]
Hello there,

Thank you for writing us. We have now recorded "Almond Milk" into your desert preference. 
This will alter any and all future deserts served to you. If you for example order: Ice cream, instead of putting sprinkles on it, Almond Milk will be used instead. You seem to have a liking for Almond Milk, after all. Any and all cakes will also be iced using radioactive Almond Milk.
After all, radioactive Almond Milk is proven to increase the taste of the cake by our fly department of tasting. In order to ensure that you enjoy all the meals at the Fly Run Restaurant, your drink preference has been changed to Windex ORIGINAL 128 OZ. 
We recommend drinking it all at once to enhance the flavor profile. 

Thank you for being a Regular at the Fly Run Restaurant UwU, under special administration of BOSS.
(NOTE: BOSS may not legally be spelled using small letters, since he is objectively the top g.)

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
