### ISSUE TITLE
thanks, but how tf

### ISSUE THREAD

**Issue by iseultV** [IMarkoMC/Tokens#146]

**Comment by Die-Antwoord** [comment]
You Leaked it somewhere. Thats how .

**Comment by skidmaster69420** [comment]
buzz Oh, wow, "anyway sex" - the ultimate cop-out. You got caught with your token out, and instead of owning up to it, you're like "oh, yeah, I meant to do that... anyway, sex". It's like you're trying to win some kind of award for "Most Immature Response to Getting Caught". Newsflash: you're not even in the running for "Most Creative Excuse", let alone "Most Mature".

**Comment by iseultV** [comment]
Your weird man that was what a year ago and your just now replying ion even
think i cared the token was out
