### ISSUE TITLE
Cool Thing pls read

### ISSUE THREAD

**Issue by WebUwU** [IMarkoMC/Tokens#15]
So you are a very very Good person im not good at Programming but....i wasnt online for 4 days and got that message i did nothing. _. So why i got message can you maybe help me anyways thats very cool that you are doing this

**Comment by IMarkoMC** [comment]
If you got a message, "your bot token was posted" that means you stored the bot token in plain text in some publicly accessible file and it was found by one of my tools.

You should use environment variables to store your token properly, storing tokens is a bad idea as everyone can see it and they can use it for whatever they want

**Comment by skidmaster69420** [comment]
**DISTRESS MESSAGE FROM SKIDMASTER69420 LLC, UNPAID INTERN**:

_MAYDAY,MAYDAY! I AM UNDER ATTACK FROM THE FLY MILITARY, THEY HAVE WEAPONIZED AGAINST US BECAUSE THE PAYCHECKS KEPT DECREASING DUE TO COLLECTED COMPANY DEBT. THERE ARE NOW TWO FACTIONS: UwU and QwQ, THE ADMINSTRATION IS BEING CHALLENGED, BOSS HAS GONE INTO HIDING. I HAVE KILLED 20 FLIES, THERE ARE 6930249 MORE! I AM OUTNUMBERED AND REQUIRE IMMEDIATE SOLITARE. TO PLAY SOMETHING DURING THIS CRISIS, PLEASE DONATE SOLITARIES TO ME NOW!_

Also, due to the Company's debt, 
BUY MICROSOFT ZUNE NOW, INFINITE POSSIBILITIES, NEW FEATURES, A HEADPHONE JACK!!!!!!!!! 
To assist the UwU Faction which is going to implement a free to use vending machines, which have all possibles kind of drinks and only accepts UwU's as payment! Meaning, if you say UwU, that's 0.01 in UwU currency. 

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
