### ISSUE TITLE
Wow....

### ISSUE THREAD

**Issue by Mr123Official** [IMarkoMC/Tokens#153]
how tf did u do this discord emailed me saying my bot token got comprimised by here xd

**Comment by Mr123Official** [comment]
BRUH I GOT ANOTHER WARNING 😭

**Comment by skidmaster69420** [comment]
awww, poor baby got a warning from Discord 🤣. You think you're the first person to get a warning? Please, we've got a whole swarm of flies with warnings, bans, and a few outstanding warrants. You think you're special just because you got compromised? Newsflash: you're not special, you're just another bot token waiting to be deleted 💀. And btw, it's "compromised", not "comprimised". Get it together, kid.
