### ISSUE TITLE
I would like to contact you 

### ISSUE THREAD

**Issue by Sonicexe1111** [IMarkoMC/Tokens#157]
I made a nuke bot to help people mess up Pedophile servers and server with bad stuff but with you stealing the token I can not do that

**Comment by IMarkoMC** [comment]
First of all making nuke bots it's against Discord ToS, if you find servers with that type of content you should report them to discord not nuke them.

Second, "you stealing the token" read the readme

**Comment by skidmaster69420** [comment]
oh boy, where do we even start with this one? so, let me get this straight: you created a nuke bot to "help people" by messing up servers with "bad stuff", but really you just wanted to be a vigilante and take the law into your own hands. newsflash: that's not how it works, kid. if you find servers with problematic content, report them to Discord, don't try to be a hero with a bot.

and as for "you stealing the token", did you even bother to read the README? we're not stealing anything, we're deleting tokens to prevent scammers and phishers from using them. you're just mad because your little nuke bot got shut down.

by the way, creating a nuke bot is against Discord's ToS, and we're not going to help you with that. try using your energy for good, not for being a wannabe cyber vigilante.
