### ISSUE TITLE
Just nice token gen bro

### ISSUE THREAD

**Issue by wdsociety** [IMarkoMC/Tokens#17]

**Comment by skidmaster69420** [comment]
**CRITICAL ERROR IN RESPONSE SYSTEM DETECTED, UNPAID INTERN HAS RUN INTO 69420 ISSUES.**
_The comment is missing a description as well as a sane person. We have made the flies aware of this terrible issue, current estimate to solve this issue_: ***2,177e+9***.

In order to bridge this time, we recommend following actions:

- Read a Book
- Watch a TV Show
- Think about the meaningless comment you made
- Reconsider your existence on this planet
- Reconsider your life choices which led you to this point.
- Write a Book about your failures in life

Due to excessive debt accumulated by BOSS's lifestyle, Skidmaster69420 LLC wishes to show you this message:
BUY A MICROSOFT ZUNE NOW! GET THE BRAND NEW TECHNOLOGY IN THE PALM OF YOUR HANDS NOW!

_Since you caused a critical error, you will not receive a nice sendoff, instead have this._
Have a terrible day.
