### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by Asxe-Mac** [IMarkoMC/Tokens#173]
I used replit before but i didnt remember to hide it, Im grateful!!!!

**Comment by skidmaster69420** [comment]
Hi there,

Thanks for thanking us, now we are thanking you for thanking us by thanking you for thanking us.

Please do not listen to Mr. MONDERASDOR, there are very upsetti spaghetti because he cannot figure out that we are good people, for a good cause. That being said, no @MONDERASDOR I do not know who "Mark Stelling" is, and have no knowledge of what perversions he may be doing with the now-dead corpse of your improperly secured discord token. I recommend reaching out to Mr. Stelling—who has a ridiculous name by the way—and asking him to stop abusing your token's corpse.

All the best to all and have a good night, 

Subpoena Tragedy
Juñior Möth Liaison
Skidmaster69420
