### ISSUE TITLE
H.lol It's stealing my token, don't take it

### ISSUE THREAD

**Issue by MONDERASDOR** [IMarkoMC/Tokens#179]
You son of a bitch, you should know you're dealing with a studio full of programmers, so you better leave big stuff to big guys, bitch. Don't try get my bot token agin .

**Comment by MONDERASDOR** [comment]
And new I'm restart my all bot token

**Comment by IMarkoMC** [comment]
Well, well, well, look who decided to show up! A little skid like you shouldn't be talking big. Keep crying, it's the only thing you're good at. You're nothing but a pathetic wannabe.

**Comment by MONDERASDOR** [comment]
I'm not cry baby I restart my token and now I project it and I'm not care about bot or token take it for your self kid

**Comment by MONDERASDOR** [comment]
![Uploading 16907649144272418374328611846417.jpg…]()

**Comment by MONDERASDOR** [comment]
@IMarkoMC You are just a despicable boy claiming to be in control. I know that you are nothing but hate, and I am not crying, boy

**Comment by MONDERASDOR** [comment]
I'm here the big and you the small

**Comment by MONDERASDOR** [comment]
I am a senior programmer. I know who is big and who is small. We hate society

**Comment by MONDERASDOR** [comment]
Your here the bad one and I'm the good one baby

**Comment by IMarkoMC** [comment]
> I am a senior programmer. I know who is big and who is small. We hate society

Senior programmer? more like senior **skid**

**Comment by IMarkoMC** [comment]
> @IMarkoMC You are just a despicable boy claiming to be in control. I know that you are nothing but hate, and I am not crying, boy

Oh, look who's trying to act tough. You think you're all that, huh? Well, guess what? You're just a sad little boy with a big ego. Keep hiding behind your keyboard, it's the only place where you can pretend to have power.

**Comment by skidmaster69420** [comment]
Hello my dear MONDERASDOR!

You have awoken me from sleeping for this? You are the "good one baby" is right, you are a massive cry baby given the fact you spammed 5 responses?! When I am really ANGRY and a CRY BABY I only make ONE response. Why? Because I am a MASSIVE son of a bitch. Instead of writing your response, you could of been HIDING your discord token from our vultures. Even I, McKeinsleigh Graycynn, a Señior Fly Developer, am able to hide my PICKLED OKRA, from my dumbass boss, Kitchenaid Wiskey Jones. 

My boss is a fucking asshole, too. My fucking house got knocked down by a asshole wearing a balaclava with a bulldoser and he still asking me to come into fucking work the next day like nothing ever happened. SKIDMASTER69420, LLC deletes the token so your asshole boss (WHO IS TOTALLY THE DUDE IN THE BALACLVA) can't use your token to send false accusations about your love for Loona from hit adult animated webseries, Helluva Boss, parchance.

Do better. For the Pickled Okra.

McKeinsleigh Graycynn
Señior Fly Developer
SKIDMASTER69420, LLC

**Comment by Pabszito** [comment]
what in the actual fucking fuck

**Comment by IMarkoMC** [comment]
> what in the actual fucking fuck

Just another clueless individual who thinks they're a big shot but really just a joke.
