### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by skiddiegit** [IMarkoMC/Tokens#2]
How much for rhe tool

**Comment by IMarkoMC** [comment]
I'm not going to sell any tools. 

The whole purpose of this project is to bother the ones stealing tokens, not selling a tool so someone can get free tokens

**Comment by unknownsrc** [comment]
#queen

**Comment by Pabszito** [comment]
:skull:

**Comment by skidmaster69420** [comment]
Hello there,

at the moment we are not selling the tool. But don't you worry, we have a much better offer for you. Introducing A45 in Germany, specifically the bridge Talbrücke Rahmede, we are offering you this bridge for the low low price of 0 dollar, simply go pick it up yourself! You'll make life easier for many german people. If this sale does not interest you, alternatively we are selling you the Deutsche Bahn... for the same price! Because they'd probably be sold than waste more of our precious budget. Any of these items will be packaged with a Laschet.
