### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by gooberboy88** [IMarkoMC/Tokens#203]
i love this but how is messing up one of my priv servers helping

**Comment by skidmaster69420** [comment]
Listen up, "lol", some jackass can find your token on the web, that's not our problem, that's your problem. Maybe instead of crying about it, you should "git gud" and learn how to actually secure your stuff. We're not here to hold your hand through basic cybersecurity 101. If you can't even be bothered to keep your own token safe, why should we care about your "priv servers"?
