### ISSUE TITLE
lol why is my token here ?

### ISSUE THREAD

**Issue by Bassil-GG** [IMarkoMC/Tokens#24]
lol why is my token here ?

**Comment by Bassil-GG** [comment]
it is just a music bot lmao

**Comment by IMarkoMC** [comment]
Read the repo readme

**Comment by skidmaster69420** [comment]
Hello there,

In order to keep my legal obligation, I will need to call you out on this. First, do not post your tokens anywhere public, make sure to have proper security on your bot. Otherwise, even though the entire company is in all out war state, the token vultures will still snatch your leaked tokens like there is no tomorrow.

Now, to update on the ongoing war. Which is bought to buy the Fly News Department (FND). However, I'll have to return to the festivities.

Yours,
Paid Intern
Skidmaster69420 LLC

**WAR AT SKIDMASTER 69420 LLC UPDATE!**
_LIVE!_

Friday, 25.10.2022 16:43 FCT (Fly Centered Time)
BOSS has retreated into the PR section of the SKIDMASTER69420 LLC. Company, his territory is now a total of 25m². The flies are celebrating this momentous accomplishment, however they are very much on guard, increasing both their defenses and offenses by employing their fully developed Anti Raid Shadow Legends Spray shields! Which has caused severe issues to BOSS'S weaponary which only consisted of 1000 Cans of Raid Shadow Legends Spray. The shields were developed by the newly founded flies science department for military advancements (FSDFMA) which was formed by Barnard Elliott Bee, III, Employee number: #69,420. They were the one to start the war to begin with, with everyone following them as they think that the number: 69,420 is the number of the chosen one.

Sunday, 13.11.2022 7:27AM
BOSS has fallen. The fly military Group #621 was able to storm the PR Department Toilet at 07:25AM. Equipped with Anti Raid Shadow Legends Spray Shields (A.R.S.L.S.S) and his own Buggati Keys. Which were aquired by Fly Military Group #392 after backing BOSS back into the PR Department. They violently stabbed the keys into the groin 7 times. After which BOSS died due to lost Pride and (lost blood). The flies celebrated the day by making it a holiday known as the Festival of RIP Bozo. 

That marked the end of the 794 hour war.

This Report was brought to you by the Fly News Department sponsored by Microsoft Zune.
