### ISSUE TITLE
Lots of people are angry at this. Why, exactly?

### ISSUE THREAD

**Issue by ApolloFujiwara** [IMarkoMC/Tokens#25]
Your token was found online by their scrapers and reposted to GitHub which forced it to be reset. That's a good thing. You want someone else to have your bot token? That of which they can use to make your bot do anything undesired? 

My bot was found, but only because I was an idiot and tried hosting on Replit. Do not use public VPS sites to host anything sensitive!

Honestly thank the team. They taught you about not leaving your token lying around like it's your car keys and prevented a disaster by resetting it for you, too.

**Comment by skidmaster69420** [comment]
Hello there, 

Thank you for replying to this issue, sadly we are still legally obligated to respond to each and every issue which were opened on the repositories we were assigned. In case you are wondering why we were court ordered to respond to all issues, here's why. BOSS illegally parked his Buggati infront of Ambulance driveways, Firestation exits, and other such vital exits. In total he did this 69420 times. Hence the "69420" within SKIDMASTER69420. The Skid, is actually refering to the fact that he has to reply to Github issues, he thinks all that use Github are Skids. The "Master" part is because he's the top G. 

If you were wondering how long the court order is to continue;
He (I) has done enough service to be pardoned for 10 of those 69420 parking tickets.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
