### ISSUE TITLE
{input title here}

### ISSUE THREAD

**Issue by Xexe2323** [IMarkoMC/Tokens#26]
I get you're trying to stop the scam bots but targeting all unverified bots (i.e. bots made for friends) isn't a good look dude"

**Comment by IMarkoMC** [comment]
1: Don't care
2: Didn't ask
3: Cry harder

**Comment by IMarkoMC** [comment]
Learn how to protect the private information

**Comment by skidmaster69420** [comment]
Hello there, 

We only report tokens that leaked, basically it doesn't even matter if your bot is verified or not. That aside, this is almost like saying "BOSS only steals their lunches from verified people", no he steals all people lunches. He does not care. Last time he stole my chicken sandwich, which I had to buy with my Inheritance from Fly #32, a good friend of mine. He left me a total of 5 dollars. He was too good to me.

R.I.P Fly #32.

That being said, I recently bought myself a verification badge. I am using it to facilitate myself as a verified "Solitaire Expert", because no one would believe me that I am a god at it. However, because of my terrible Solitaire skills... I am being sued by the International Solitaire Company. 


Yours,
Unpaid (Mourning, In a lawsuit) Intern
SKIDMASTER69420 LLC.
