### ISSUE TITLE
Thanks for doing god work!

### ISSUE THREAD

**Issue by yohohoyu** [IMarkoMC/Tokens#27]
Bro thank you i do not know what I could do without your help. i would not even know this happened! THANKS!!!!!

**Comment by Corey-Stowe** [comment]
Yeah, when my Messaging bot token was leaked, Discord noticed me and linked this repo, and I was think why my token was leaked, and the answer was: I forgot to trun  private mode in repl repo, so my bot token was published in here. Thank you so much if this repo is invalid and I don't know my bot token was leaked.

**Comment by skidmaster69420** [comment]
Hello there,

We wish to thank you for being so kind. In fact, because Unpaid Intern rarely actually gets meet with kindness. He sort of passed out, hence a fly department of appreciation was founded to deal with friendly messages. Therefore, we wish to hereby thank you for thanking us. Now that may sound like a tongue breaker, well it may be. But we do mean it. Stay awesome :)

Yours,
the newly found Fly Department of Appreciation  (Fly #32349)
SKIDMASTER69420 LLC
