### ISSUE TITLE
not good

### ISSUE THREAD

**Issue by odavido656** [IMarkoMC/Tokens#28]
your not good

**Comment by Angry-Pineapple3121** [comment]
You fool. You complete and utter imbecile. You absolute fucking moron. Have you even passed an English class once in your miserable, pathetic fucking life? How could you be so stupid, so profoundly brainless, as to mistake “your” for “you’re”? I’d have forgiven you for saying “ur” instead of making the nonsensical blunder of misusing the word “your”, because at least then you demonstrate that you don’t care about grammar. But you? No. You decide to give it a fucking shot, and look where that got you. You actually attempted to use the proper form of the word, you took the extra time to think it out, but in that extra time you spent thinking and typing, you somehow manage to fail at the simple task of using the correct form. It’s not a matter of lack of effort, it’s a matter of your distinct lack of a functioning brain. You are simply so unbelievably stupid, that you can’t even begin to understand, much less use, the simplest of rules within the English language. How did you manage to even get on this site? Judging from your single digit IQ, I’d be surprised if you haven’t forgotten how to breath half way through this message. My best guess is that, by some bizarre and miraculous serious of random events, a malformed half-human managed to open a phone or computer and shit out that miserable excuse for a sentence. I hope that your descendants, assuming anything is willing to procreate with your vile, disgusting being, manage to evolve to a point where basic fucking English is at least partially within their grasp. Close this site right fucking now; I can’t bear to think that your complete void of intelligence might corrupt some poor, innocent bystander, forever robbing them of the ability to make rational thought.

**Comment by YJB69** [comment]
To let you know, you did not put a D after the word, "manage.", to add, you failed to pluralize the word "thought" as well, along with the constant run on misuse of words you constructed. Furthermore, putting "serious" rather than "series" shows your ignorance. I am not a grammar whore. but trying to correct GitHub comments demonstrates your own insecurities. When people write comments, grammar/spelling are not incredibly important to them. Instead, they focus on their message or point. Trying to point out grammar mistakes, while you clearly haven't passed 5th grade, is pretty entertaining for me. While I'm all for people using the correct forms of words, calling them out doesn't demonstrate intelligence, but rather shows the lack of purpose you have in your own life. You spend time on GitHub correcting people's grammar for no reason, other than attempting to fill the void left behind from the lack of attention you get. I would suggest debating people with ideas and counter-arguments, rather than pointing out trivial mistakes that have no effect on the overall message that the person is stating.

**Comment by skidmaster69420** [comment]
Hello there, 

_Foreword from BOSS_
I usually let Intern deal with these fucken posts, however I found your reply so funny. I had to reply to you, well not really. I let intern write the text, but inserted my greeting and foreword. Why? Because I am the motherfucking top G. Now have fun reading that virgins explanations and shit, I need to get back to my Buggati.

Thank you Dr. @YJB69 in English Grammar. You have not only noticed a critical mistake with the above post, to which you are referring here. You also tried to initiate a debate here about how we shouldn't be judging someone based on their grammar. Which is something that we of course shouldn't be doing. 

However let me also mention here that the original Poster, only said "your not good". This does not leave much room for an actual deliberation or discussion. Thus the poster after decided to be satirical by taking a well known "Copypasta" and editing it so that it fits this context.

Now, however Dr. @YJB69, the Fly Department of Educational Supervision has launched an internal Investigation on your post. It has determined that you didn't capitalize "but" at the beginning of your sentence. To avoid any confusion. A beginning of a sentence is initiated either at the very beginning of a text, or after a dot (.). In Line 4 of your post "grammar whore. but" As you can see, the "but" is clearly not capitalized, meaning there is a grammatical error here. 

This in turn lead the FDES to contact your University, after even more research it turns out that all the research you had handed in was all copied from Wikipedia 1 to 1. Thus your PhD in English Grammar has been revoked. This decision cannot be appealed.

Thank you,
BOSS
SKIDMASTER69420 LLC.
