### ISSUE TITLE
WHY MY TOKEN HERE?!

### ISSUE THREAD

**Issue by GuestAnimationsHD** [IMarkoMC/Tokens#29]

**Comment by IMarkoMC** [comment]
Maybe if you had more than 1 IQ you will able to read the readme and figure out that question by yourself

**Comment by skidmaster69420** [comment]
Hello there,

Due to the very low IQ that this posts radiates, we hereby wish to let you know that the Fly Department of Animation is hereby cancelling the contract, which we had with you to make an Animation for us. 

Furthermore, the Fly Department of Financial Analysis has taken a look into your recent performance. Declaring Bankruptcy is hereby being highly advised.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
