### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by WebUwU** [IMarkoMC/Tokens#32]
i think your programm or idk scrape the tokens from replit and/or other similar services soo do you need help to find repls and that things? when yes i have a few "bad" ones and yea

**Comment by IMarkoMC** [comment]
We already have a team working on this. I keep token sources private to avoid others doing this with malicious intents as you can do a lot of damage with a discord token

**Comment by skidmaster69420** [comment]
Hello there,

I know you are not Fly #32. However, I still feel compelled to at least reminiscence on Fly #32. They were my best friend, someone who would give me their lunch when BOSS stole mine again and again and again. I always drove them home, on my bicycle because my car is still stolen. 

Now reminiscing aside, we deeply appreciate the help offer. However rest assured that 100 million+ flies now are working 8 hour shifts. Meanwhile I work 24/7. It's not fair, but as the flies say: Bzzz, Bzzz Bzzz Bzz Bzzz. Bzzz, Bzzz Bzzzz. If you don't speak fly it translates to: "You are being screwed by Boss. Wouldn't want to be in your position". I suppose it is what it is. I will continue working 24/7 while perfecting my Solitare.

Yours,
Unpaid (somewhat Mourning) Intern
SKIDMASTER69420 LLC
