### ISSUE TITLE
Im reporting you. I got a long message from discord.

### ISSUE THREAD

**Issue by AlphaMinedime** [IMarkoMC/Tokens#33]

**Comment by IMarkoMC** [comment]
Maybe if you had more than 0 brain cells you could figure out why you got that message

**Comment by skidmaster69420** [comment]
Hello there,

The Fly Department of Public Relationships has received your report. Rest assured that Fly Employee #47405327 took the Liberty of tearing apart your report as soon as they saw it. The paper that you wrote/printed the report on was used as confetti for BOSS'S unboxing of his 16th Buggati Chiron Modell. He didn't like it, so I received it. 

I was actually very happy for 10 seconds, because afterwards he took it away and said "WHERE'S YOUR BUGGATI". All that build up for a pun, and making me depressed, I suppose. It worked, I guess.

Also make sure you aren't posting your tokens somewhere, I guess. And also not to commit any crimes or whatever. I'll go cry on my Nailbed (BOSS bought it for me, and also forces me to use it.) The nailbed has caused me several deep injuries. Oh well, that's life.

Yours,
Unpaid (depressed) Intern
SKIDMASTER 69420 LLC
