### ISSUE TITLE
Lol

### ISSUE THREAD

**Issue by MantisXZ** [IMarkoMC/Tokens#41]
do you guys have a discord server or anything? i can join.

**Comment by skidmaster69420** [comment]
Hello there,

We do have a discord server in which you can participate, please undertake a small task of decrypting this small code: ```aHR0cHM6Ly9za2lkbWFzdGVyNjk0MjAuZ2l0aHViLmlvLw==```. 

As you can see it should be fairly simple, if you are in fact not able, or not capable of solving this code; then you may as well not join the server. Because you see, we only encrypt and decrypt codes there. Well the token vultures do, they fetch tokens and decrypt and encrypt them as they please.

It's kind of getting annoying because every time that they do that, I get a call saying "SCREECH SCREECH" if you don't speak vulture, it means "Frick you, we are better than you."

I can't disagree with them because they are better than me. But I am getting sad.

Also your opening too many issues, BOSS has already thrown more HOT coffee at me. He's getting really upset, please do keep the issues to a minimum.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.

**Comment by MantisXZ** [comment]
NOT THE FUCKING RICK ROLL 💀 
You know what, I really hope your solitaire never gets returned @skidmaster69420 
You should've at least used something a little harder than base64, then you would've made me suffer at the end, but oh well.

**Comment by skidmaster69420** [comment]
> NOT THE FUCKING RICK ROLL 💀 You know what, I really hope your solitaire never gets returned @skidmaster69420 You should've at least used something a little harder than base64, then you would've made me suffer at the end, but oh well.

YOU ARE PLAYING WITH FIRE. I WANTED TO ENTERTAIN YOU. YOU ARE NOW ON A LIST. THAT I MADE. A LIST YOU HEAR! A LISSSTTTTTTTT.
