### ISSUE TITLE
Lmao

### ISSUE THREAD

**Issue by MakeSureDudeDies** [IMarkoMC/Tokens#44]
Ok that was funny, my thing wasn't a prishing or anything but it was a bot i used to joke around with friends...

guess i have to secure my thing harder

**Comment by IMarkoMC** [comment]
You have a guide on how to protect your secrets using env variables in this repo

**Comment by MakeSureDudeDies** [comment]
> You have a guide on how to protect your secrets using env variables in this repo

alright thanks lol

**Comment by MakeSureDudeDies** [comment]
I will also keep up with this repo, its funny to see people cry over thier server being "destroyed with unwanted content" (nsfw)

**Comment by IMarkoMC** [comment]
> I will also keep up with this repo, its funny to see people cry over thier server being "destroyed with unwanted content" (nsfw)

This repo is just a **token deletion repo** as the [readme](https://github.com/IMarkoMC/Tokens/blob/main/README.md) says. I'm not doing anything against Discord ToS (raiding/sending unsolicited dms/unwanted content) but if someone else finds the token and raids the server there's nothing i can do more than uploading it to github to make it invalid

**Comment by MiracleCherryPie** [comment]
Token deletion repo heh? I think one or more token in this repo still functioning

**Comment by IMarkoMC** [comment]
> Token deletion repo heh? I think one or more token in this repo still functioning

They are deleted by discord once they're detected. It's nearly instant

**Comment by MiracleCherryPie** [comment]
If you want to block me, go ahead

**Comment by MiracleCherryPie** [comment]
Security is more important

**Comment by IMarkoMC** [comment]
> Security is more important

Posting a token to get it invalidated without breaking Discord ToS is the fastest way to avoid someone else using a bot token for something else

**Comment by MiracleCherryPie** [comment]
I'm not dumb enough but still, try think harder to invalidate bot token in any way

**Comment by IMarkoMC** [comment]
> I'm not dumb enough but still, try think harder to invalidate bot token in any way

There's no other way within Discord ToS. Continue crying

**Comment by MiracleCherryPie** [comment]
I'm not crying yet

**Comment by MiracleCherryPie** [comment]
But you guys should be cry

**Comment by IMarkoMC** [comment]
> Should be cry?

Your IQ is so low that you cannot even write a proper sentence.

**Comment by IMarkoMC** [comment]
> Honestly, English is NOT my native language but there's still a button to shutdown this repo

I will not shutdown this repo. You can complain all you want.

**Comment by Whanos** [comment]
> I'm not dumb enough but still, try think harder to invalidate bot token in any way

This literally is the fastest, easiest, and most TOS compliant way to invalidate a token.

**Comment by SkidMasterHoldingsLLC** [comment]
Hello,

You've reached the automated complaints department of SkidMaster Holdings LLC.
If you'd like to complain about our revolutionary, top of the range token dejigamaflipper, please reply "YES" to this message.

Thanks,
Alan
[BOT]
_This message was definitely automated._

**Comment by Whanos** [comment]
> Ah yes nEArLy InsTAnT ThEY dEleTeD tHE t0kEn in 5 sEc0nds !!1!1!!1!1!1!1!1!1!1!1!1
> 
> Also, why you make this repo? why not make something better? If you want to warn replit users if their token got leaked, comment at their repl or try to invalidate them.

When a token is uploaded here and invalidated by discord, the user who owns the bot gets a DM from Discord explaining as such. They then get linked here, which contains information on what to do.

**Comment by aamiaa** [comment]
> Ah yes nEArLy InsTAnT ThEY dEleTeD tHE t0kEn in 5 sEc0nds !!1!1!!1!1!1!1!1!1!1!1!1

GitHub has something called [Secret scanning partner program](https://docs.github.com/en/enterprise-cloud@latest/developers/overview/secret-scanning-partner-program) which allows services like Discord to request github to scan all repositories for specific matches and report to their callback url _instantly_. It's precisely what Discord uses to invalidate tokens posted on GitHub in realtime.

**Comment by IMarkoMC** [comment]
Yes

**Comment by SkidMasterHoldingsLLC** [comment]
Thank you for opting in to learn more about our dejigamaflipping techniques.

We're the leading organisation in the dejigamaflipping industry. We work with all kinds of dejigamaflipping methods to dejigamaflip misplaced tokens and prevent abuse.

If you'd like to see our official certificate from the International Commission on Dejigamaflippage, see attached. ![SKDMSTR_CERT_19](https://i.imgur.com/rrsh06l.png)

Want to learn more? Reply "YES"!

Thanks,
Alan
[BOT]
_This message was definitely automated._

**Comment by IMarkoMC** [comment]
Yes

**Comment by SkidMasterHoldingsLLC** [comment]
Thank you for opting in to learn more about SkidMaster Holdings LLC.

We're the hard workers that manually sit through and read every GitHub repo and Replit repl to absorb any token or webhook we come across. So far, we've read through over **1,000,000** lines of code. Want proof? Look at this **tally counter** we manually click **+** every time we read a line of code! 
<img width="357" alt="image" src="https://user-images.githubusercontent.com/119431753/204571669-257cb4bd-5d31-4412-bb32-70f0bdb62de4.png">

**Please note:** We are NOT to be mistaken with skidmaster69420 LLC, who are our biggest rival. They eat up all of the tokens and webhooks before we can! This makes Alan sad and cry at night. (◡︵◡)

Thanks,
Alan
[BOT]
_This message was definitely automated._

**Comment by skidmaster69420** [comment]
[Fly Department of Public Relations]

Greetings,

Unpaid Intern is currently not available to respond to the issue. However as the court order demands that we answer to all and any issues opened, we are hereby doing said task for him. We have taken notice of the stupidity of a commenter here, who is accusing this Repo of not being sufficient. This is frankly, untrue. This Repo has helped keep many tokens secure, which happened to be leaked.

It is not our responsibility to send a warn message to every single person who had their token leaked, since that is first off not even possible. However we can help them not get their bot stolen, which this Repo is here for.

The educational breakdown aside, we also wish to leave a "satirical comment" as Unpaid Intern does, so that even though in his absence, the contents of the messages do not lose in quality.

For this purpose we'll be comparing your stupid idea to that of a house burglary. Basically, having your token leaked is almost like losing your key. We basically terminate the lock so that your lost key can't be used to open your house. You instead want us to warn you, but still have your house broken into.

We are not if that's a financially reasonable idea.

We have taken Notice of SkidMasterHoldings. Please be advised, that we do not do this for competition. We do this in order to get the Parking Tickets of BOSS paid. Once that is done, we will probably dissolve. Though that remains to be seen.

Sincerely,
Fly Department of Public Relations
SKIDMASTER69420 LLC
