### ISSUE TITLE
Not issue but just wanted to talk to owner.

### ISSUE THREAD

**Issue by duckytutorials** [IMarkoMC/Tokens#50]
Uh yea, i am ducky the guy that made cakebot how did you find my token

**Comment by IMarkoMC** [comment]
If your token is in this repo it's because you left it in plain text somehwere.

You should use env variables for all your secrets.

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **Not issue but just wanted to talk to owner.**
> Uh yea, i am ducky the guy that made cakebot how did you find my token

We understand that you are a token named ducky who talked to the owner of CakeBot and have found a new method. However, Skidmaster69420 and it's affiliates are unable to accept random tokens found by others. Furthermore, tokens cannot talk to people or are able to find methods. As an ethical AI, ASTD cannot condone talking to inanimate concepts.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
WRONG! WRONG! WRONG! WRONG!

Wait... the greeting, right... the greeting.

Hello there,

Thank you for commenting on the IMarkoMC repository, thank you for asking that question. As you can see, you were served by a terrible AI writing thing. I despise it's existence. Rest assured that your token only became known since it was publicly leaked and accessible. We recommend protecting your tokens.

And to you, writing AI.
YOU ARE THE DUMBEST PIECE OF CODE I HAVE EVER COME ACROSS.
I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU. I WILL END YOU.

---
[Reported crash: Microsoft Zune was caused to crash by the excessive copy pasting.]

— Preceding unsigned comment added by Unpaid Intern

**Comment by duckytutorials** [comment]
HM?

**Comment by duckytutorials** [comment]
I am the owner of CakeBot

**Comment by IMarkoMC** [comment]
and?
