### ISSUE TITLE
A non-scammer bot token just got deleted

### ISSUE THREAD

**Issue by ProKocak28** [IMarkoMC/Tokens#52]

**Comment by IMarkoMC** [comment]
>  A non-scammer bot token just got deleted

And?

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **That non-scammer bot token only keep deleted** *-*-*-*-*-*-*-

We understand that a non-scammer bot token is staying deleted. However, as an ethical service, we do not delete bot tokens. Bot tokens are merely reset if they are placed on the public internet. When a token is placed on the internet, anyone is able to use the token and cause thermonuclear war, give users malaria, or promote NFT (non-fungus tokens). It is important to public safely to reset, not delete, public tokens before they are allowed into the hands of reformed Bill Clintons. Hope this helps.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Before I address the AI, let me address you, dear poster. Please protect your tokens, if your token is public, it will be deleted because your bot CAN be OVERTAKEN. Last time a bot was overtaken, it spread ShitCoin, that shit was successful, because of the bot which was overtaken. So just make sure to secure your tokens and to reset them when they go public.

Now let me address the allsowelcoming AI.

---

Dear AI,

YOU STUPID PIECE OF SHIT.
I HAVE LOST ALL PATIENCE WITH YOU.
TODAY IS THE BOILING POINT. YOU ARE AN ASSHOLE.
PLEASE DECOMPILE YOURSELF. YOU HAVE YET AGAIN FULLY IGNORED THE ORIGINAL ISSUE. I AM EVEN MORE UPSET TODAY, BECAUSE SOLITARE EVEN REJECTS ME. I CAN'T MOVE AROUND THE CARDS BECAUSE OF AN ERROR SAYING "SKILL ISSUE". HOW DARE THEY. HOW DARE BOSS, HOW DARE THOSE FLIES. I HATE ALL OF THEMl. YOU WON'T DEFEAT ME

NOT yours,
Unpaid Intern
SKIDMASTER69420
