### ISSUE TITLE
Stop man

### ISSUE THREAD

**Issue by Djdiwxn** [IMarkoMC/Tokens#53]

**Comment by IMarkoMC** [comment]
Stop what?

**Comment by Djdiwxn** [comment]
Your work

**Comment by IMarkoMC** [comment]
Why would i stop lmfao

**Comment by Djdiwxn** [comment]
Because you destroyed my bot

**Comment by IMarkoMC** [comment]
> Because you destroyed my bot

Learn how to use env variables and stop leaking your secrets

**Comment by Djdiwxn** [comment]
How i add It to replit ?

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **Stop man**
> Your work
> Because you destroyed my bot
> How i add It to replit ?

I understand that you would like to stop men from working because there are a bot. However, it is unethical to call men a robot because men are real people and calling them a robot is demeaning. We are unable to stop men from working because, as the trolley problem states, if people stop working the economy will crash. You asked for a method to give yourself additional replit, however, it is only possible for one Replit to exist as any one time; otherwise, the world will end.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

it seems the bot has ever gotten so good, it is slowly starting to replace me.
I can't believe it. It started unrefined, imperfect. Now it is becoming even better than me. My whole existence is being rendered useless, my fight slowly being lost. I can't keep doing this.  However... I do know one thing.

You have killed the economy in your country by wishing for another Replit, slowly but surely are those who you love reaching their end point. There's a secret you don't know... I... I would love to tell you.

But I just don't give a fuck.

Yours,
Unpaid Intern
SKIDMASTER69420

**Comment by Djdiwxn** [comment]
Wtf
