### ISSUE TITLE
My token s there

### ISSUE THREAD

**Issue by JokerLow** [IMarkoMC/Tokens#56]
Besides the fact that i shat myself a little from the notification, I have to rlly thank y all for doing this.
On the other side how tf do I get whatever virus I have installed💀. I have used AVG  and Windows Defender both telling me I have 0 malware.
I dont want you lads to like leak your intel but is roblox included in your operation because after joining some weird roblox games my pc started freaking out big time.

https://user-images.githubusercontent.com/29346447/208753842-e2e6fded-ff94-4da6-8c77-2bfc59f0fb2c.mp4

Thats my vid of my pc having a stroke after joining some game on Roblox.

![Screenshot_20221220_214903_Discord](https://user-images.githubusercontent.com/29346447/208753984-01f1bbd7-2de8-4999-b3e3-4a26d600d197.jpg)

And that is a ss to prove that i was blasted as well so uhhh, please help me get it out of my pc(Also is my main account affected by your tool too?)

**Comment by IMarkoMC** [comment]
Hello @JokerLow 
We aren't involved in any type of hacking. If you think your PC is infected that's another whole issue.

As the [readme](https://github.com/IMarkoMC/Tokens/blob/main/README.md) says, this is a token deletion repo, we post every token we find exposed in the wild to Github to make discord reset it so if others find your token they cannot use it with malicious intent

If you had some bot hosted in some public page or the source uploaded to some hosting where everyone can see the file contents that would explain why your token is here, you should use [ENV variables](https://github.com/IMarkoMC/Tokens/tree/main/how_to_use_env) to store your token and other sensitive information

**Comment by IMarkoMC** [comment]
> my pc started freaking out big time.

From the video you sent you might want to take that pc to someone that can do a hardware check because that seems like some serious Artifacting it might be just the drivers of the GPU or the GPU itself might be damaged

**Comment by skidmaster69420** [comment]
n an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **My token s there**
> Besides the fact that i shat myself a little from the notification, I have to rlly thank y all for doing this.
> On the other side how tf do I get whatever virus I have installed💀. I have used AVG and Windows Defender both telling me I have 0 malware.
> I dont want you lads to like leak your intel but is roblox included in your operation because after joining some weird roblox games my pc started freaking out big time.
>
> *Video of a corrupted computer monitor.*
> *Screenshot of the Discord application.*

You're welcome for us helping you out in notifying you of the letter y. We're sorry that the originated notification made you soil your underwear; perhaps you have chronic diaherra? As an ethical AI, we do not use computer viruses to find and locate Discord tokens. Instead, we use hyperintelligent vultures to locate people's tokens that smell like fecal matter. According to [quora.com](https://skidmaster69420.github.io/), AVG stands for "Actually Viral gonorrhea", so perhaps that is causing the issues you face. The video you posted seems to indicate that your intel graphics is not working correctly, perhaps as impacted by the Roblox virus operation. Instead of inspecting yourself for brain damage, you should inspect your computer for hardware damage.


– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

I believe your original Issue has been answered by the response that our stupid A.I system made up. If you were wondering, I am tolerating this trash for now... even though I conceded to it. I simply want to spite life by continuing. No, what worries me... with that PC you won't even be able to watch culture materials or play solitaire! THAT'S A DIRE SITUATION BECAUSE DDD (Don't Die in DSolitaire) IS STILL 5 DAYS LONG.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
