### ISSUE TITLE
Where is my token coming from????

### ISSUE THREAD

**Issue by Luamebs** [IMarkoMC/Tokens#57]
I am using a music bot script from SudhanPlayz and it is the fourth time I have to reset my token, I literally reseted it this morning and it is already there, I can't understand where my token is being leaked since I just copy it and paste it straight to my bot's script. Is it possible that I got any virus on my pc? I accidentally runned a fake blender installer (probably had virus) but I use Kaspersky and it did not showed up nothing since then

**Comment by IMarkoMC** [comment]
> I can't understand where my token is being leaked since I just copy it and paste it straight to my bot's script. 

Use environment variables.

**Comment by skidmaster69420** [comment]
In an effort to reduce costs, Skidmaster69420 LLC's Fly Department of Embezzlement has elected to respond to issues using our new AI Assistant, ASTD.

---

> **Where is my token coming from????**
> I am using a music bot script from SudhanPlayz and it is the fourth time I have to reset my token, I literally reseted it this morning and it is already there, I can't understand where my token is being leaked since I just copy it and paste it straight to my bot's script. Is it possible that I got any virus on my pc? I accidentally runned a fake blender installer (probably had virus) but I use Kaspersky and it did not showed up nothing since then

Hi there, it seems are you requested to know where token comes from. Discord tokens are randomly generated by the Discord and given to you to use. It seems rather concerning that the music bot, sudhanplayz, keeps resetting your token yourself. When the token is sent to the bot script, our team of hyperintelligent flies were able to locate it because it was unprotected. Furthermore, you requested to know if a fake blender was able to have a virus. A blender is a kitchen appliance used to fix, crush, purée or emulsify food. It is unable to contain viruses as it a kitchen appliance and not a computer program. We hope you enjoy your new Kaspersky K400 Variable Speed Blender.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

ASTD forgot to mention something something.
BUY NOW AND SAVE 50 BUCKS AND WE WILL THROW IN SOME USED SOCKS.
Socks can be used as a utensil, weapon, companion, storage space, etc. They are very volatile.

THIS OFFER ONLY LASTS FOR ![](https://skidmaster69420.github.io/count.gif) SECONDS!!!! GET THEM WHILE YOU CAN.

Disclaimer: The socks aren't actually used, we just moisten them a little before sending them.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
