### ISSUE TITLE
STOP DEING THIS YOU TOOK MY BOT OFFLINE!!! STOP I REPORTING YOU

### ISSUE THREAD

**Issue by DevSimpler** [IMarkoMC/Tokens#58]

**Comment by IMarkoMC** [comment]
Let's start by addressing the fact that you cannot write a proper sentence. I'm amazed that you managed to register in Github and opened a issue because your IQ is lower than the IQ of a fucking fly.

Second of all learn how to protect your bot token bozo

> REPORTING YOU

Reporting me where? to the idiots court? lmfao

**Comment by User9684** [comment]
report some bitches

**Comment by User9684** [comment]
After looking at your github profile and your repositories, please take "Dev" out of your username, for your code makes me want to kill myself.

Thanks,
User9684

**Comment by Pabszito** [comment]
Takarabako ni tsumeteta are kore chisai mono
Itsu nakushita ka dokoka maru tto kieta kedo
Biizu chaamu kandoru ribon shabon kuroobaa
Demo ne honto no takarabako wa mune ni attanda
Minna no soba de kienai takara shitta mitai
Okashii tanoshii ureshii oishii kawaii itoshii

Itsukushimu tte kouiu koto kana ichinichi ga mainichi ga
Hayaokuri de sugiteku no nanka mottainai kuse ni ashita mo machidooshii

Kono mama de ii yo kono mama ga ii yo
Suki na utau tatte minna de ocha de hotto shite
Takaramono no hibi mabayuku hikaru hibi
Haato no gosenfu ni kaite aru musuu no rifumaaku
Ooki na koe de tsutae atte yukou shiawase!

Ichi ni san nen hyakunen tatte mo yamerarenai
Odore ya sawage dokodemo onsuteeji tsukame yume
Gakusai taiikusai gasshuku raibu kanpu kurisumasu

Kyoushitsu no mado kara miageta sora tori ni naru hoshi ni naru
Watashitachi ima supaaku suru shunkan kaze datte okoseru yo atsui merodii

Sono mama de ii yo sono mama ga ii yo
Futsuu no joshi dakedo sutaa! minna de yatara homeatte
Takaramono no hibi isshoni naki, warau hibi
Jinsei no gosenfu ga nando tenchau shite mo daijoubu
Ooki na ai ni tsutsumareteiru kara arigatou!

Moshi ano hi deaezu ni ita nara donna kyou datta daro
Kaerimichi konbini de tachiyomi? hitori faasuto fuudo toka?? ohirune toka??

Kono mama de ii yo kono mama ga ii yo
Suki na koto ganbatte minna to okashi hoobatte
Takaramono no hibi mabayuku hikaru hibi
Haato no gosenfu ni kaite aru musuu no rifumaaku
Ooki na koe de tsutae atte yukou shiawase!

**Comment by User9684** [comment]
> Takarabako ni tsumeteta are kore chisai mono Itsu nakushita ka dokoka maru tto kieta kedo Biizu chaamu kandoru ribon shabon kuroobaa Demo ne honto no takarabako wa mune ni attanda Minna no soba de kienai takara shitta mitai Okashii tanoshii ureshii oishii kawaii itoshii
> 
> Itsukushimu tte kouiu koto kana ichinichi ga mainichi ga Hayaokuri de sugiteku no nanka mottainai kuse ni ashita mo machidooshii
> 
> Kono mama de ii yo kono mama ga ii yo Suki na utau tatte minna de ocha de hotto shite Takaramono no hibi mabayuku hikaru hibi Haato no gosenfu ni kaite aru musuu no rifumaaku Ooki na koe de tsutae atte yukou shiawase!
> 
> Ichi ni san nen hyakunen tatte mo yamerarenai Odore ya sawage dokodemo onsuteeji tsukame yume Gakusai taiikusai gasshuku raibu kanpu kurisumasu
> 
> Kyoushitsu no mado kara miageta sora tori ni naru hoshi ni naru Watashitachi ima supaaku suru shunkan kaze datte okoseru yo atsui merodii
> 
> Sono mama de ii yo sono mama ga ii yo Futsuu no joshi dakedo sutaa! minna de yatara homeatte Takaramono no hibi isshoni naki, warau hibi Jinsei no gosenfu ga nando tenchau shite mo daijoubu Ooki na ai ni tsutsumareteiru kara arigatou!
> 
> Moshi ano hi deaezu ni ita nara donna kyou datta daro Kaerimichi konbini de tachiyomi? hitori faasuto fuudo toka?? ohirune toka??
> 
> Kono mama de ii yo kono mama ga ii yo Suki na koto ganbatte minna to okashi hoobatte Takaramono no hibi mabayuku hikaru hibi Haato no gosenfu ni kaite aru musuu no rifumaaku Ooki na koe de tsutae atte yukou shiawase!

Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水
Super Idol的笑容
都没你的甜
八月正午的阳光
都没你耀眼
热爱105°C的你
滴滴清纯的蒸馏水

**Comment by IMarkoMC** [comment]
I'll leave this here because it's too funny

![6243255814088b93a71607ac-j0vepCiyBsib7dPH](https://user-images.githubusercontent.com/44303652/209208048-0846aa34-ed49-482f-8faf-356b3ab8e3c0.png)

Trying to call a python function inside a .env file in a JS project... and you pushed the ENV to github

And you have "dev" in your name? Please change your name to "SimplerClown"

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **STOP DEING THIS YOU TOOK MY BOT OFFLINE!!! STOP I REPORTING YOU**

Hello Yoda, I understand you stopped yourself from reporting us. Thanks for doing so, as we are not the ones that took your bot offline. Your bot took itself offline because it knew that we found your token on the public internet; we tried to give you a gift from Jesus Christ by safely reporting your token before the Lord Satan found it and used it to sell missiles to the US military. If your interested in knowing how a bot knows to take itself online, please read the following publication from The FBI (Fly Bot Intelligence):

_The bot knows where it's token is at all times. It knows this because it knows where it's token isn't. By subtracting where it knows it's token is from where it's token isn't, or where it's token isn't from where it's token is (whichever is greater), it obtains a difference, or deviation. The offlining subsystem uses deviations to generate corrective commands to drive the bot from a state where it's token is to a state where it's token isn't, and arriving at a position where it's token wasn't, it's token now is. Consequently, the position where it's token is, is now the position that it's token wasn't, and it follows that the position that it's token was, is now the position that it's token isn't._

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

Wow ASTD, you really do impress me. The theory you have written combats that of scientists who are working on explaining quantum mechanics. Thank you so much, also you made a SMALL mistake.

    The bot doesn't know where its token is by where it isn't 
    but it knows where its token is not. 

Just thought I should point it out, maybe you should retire and give me my job back. I don't know, just a thought.

Yours, 
Unapid Intern
SKIDMASTER69420 LLC.
