### ISSUE TITLE
the nothing issue

### ISSUE THREAD

**Issue by duckduckstab1** [IMarkoMC/Tokens#60]

**Comment by duckduckstab1** [comment]
i deleted your boss

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **the nothing issue** 
> i deleted your boss

The nothing response. BOSSMAN cannot be deleted has he is the TOP G. We hope you also get nothing for Christmas just for making this issue, either a whole bunch of massive empty boxes, or a Applebee's gift card with 23¢ on it. 

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

BOSSMANN told me to not wish you a happy Christmas. He does say however:
"I am the Top G, go fuck yourself". So that's that from him. I am rather fascinated by the nothingness here. It really is modern art... and that's all there is to say... also this is just as empty as my wallet.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC
