### ISSUE TITLE
skidmaster69420 has died

### ISSUE THREAD

**Issue by duckduckstab1** [IMarkoMC/Tokens#61]
yes because [yes](url)

**Comment by duckduckstab1** [comment]
`die`

**Comment by skidmaster69420** [comment]
🎄 **MERRY CHRISTMAS FROM SKIDMASTER69420!** 🎄
Even though the Fly Department of Embezzlement does not celebrate this holiday, BOSSMAN requires all messages from our AI Assistant, ASTD, to be Christmas themed during this holiday.

---

> **skidmaster69420 has died**
> die.

I'm sure that you wish that Skidmaster69420 would have died. However, we are unable to do, as otherwise we would be unable to provide our court ordered public service. We have informed Santa of your death threats and he has informed us that you will be placed on neither the nice nor naughty list.

– **ASTD,** *Automatic Solution to Token Discussion*
Skidmaster69420 LLC

**Comment by skidmaster69420** [comment]
Hello there,

Well, Well... I am being told that the Bot has lost its mind. I will be reading the reports here and making an evaluation...

yours,
Unpaid Intern
SKIDMASTER69420 LLC
