### ISSUE TITLE
my private bot token

### ISSUE THREAD

**Issue by ReflexTheLegend** [IMarkoMC/Tokens#65]
wtf is my bot's token doing there
![image](https://user-images.githubusercontent.com/70488503/209463974-1823337c-6327-490a-9632-38e39c491b9d.png)

**Comment by IMarkoMC** [comment]
> wtf is my bot's token doing there

Do not save tokens in plain text. Use ENV variables

**Comment by gevo507** [comment]
mine too tf is that
![Screenshot_25](https://user-images.githubusercontent.com/52261530/209478430-4ef35366-e018-4c69-ad14-7c0ecd5268da.png)

**Comment by skidmaster69420** [comment]
Hel- I don't even need to greet you,

They can't do SHIT. They can't fire me, they can't control me. I don't need to listen to the standard guidelines no more. They don't have an replacement ready, the A.I is down and the debt is accumulating from having even run that thing. They can't even afford to let the FDPR respond to the issues, because they actually demand money! I don't, I simply want my Solitaire, that's enough for me. So now, I have complete control in addition to the basic meals and tap water that I get every once in a while. 

I AM FULLY BACK BABYYYY

NEVER YOURS,
Unpaid Intern
SKIDMASTER69420 LLC

**Comment by ReflexTheLegend** [comment]
> Hel- I don't even need to greet you,
> 
> They can't do SHIT. They can't fire me, they can't control me. I don't need to listen to the standard guidelines no more. They don't have an replacement ready, the A.I is down and the debt is accumulating from having even run that thing. They can't even afford to let the FDPR respond to the issues, because they actually demand money! I don't, I simply want my Solitaire, that's enough for me. So now, I have complete control in addition to the basic meals and tap water that I get every once in a while.
> 
> I AM FULLY BACK BABYYYY
> 
> NEVER YOURS, Unpaid Intern SKIDMASTER69420 LLC

bro who the fuck are u lmao
