### ISSUE TITLE
holap

### ISSUE THREAD

**Issue by PolBruno** [IMarkoMC/Tokens#67]
Quitar esto porque, según Discord, "publique" el token de mi bot (personal) y le dio un 'strike' a mi cuenta de manera injusta.

**Comment by IMarkoMC** [comment]
"Remove this because, according to Discord, I "posted" my (personal) bot's token and it unfairly 'strikeed' my account."

Are you brain-dead or what m8?

Also no, Your token won't be removed and i won't stop the scanners. 

Learn how to code properly and don't leak your bot token

**Comment by PolBruno** [comment]
But I never leaked it

**Comment by IMarkoMC** [comment]
> But I never leaked it

You leaked it. And i found it there's no black magic in scanning the whole internet for files containing tokens

**Comment by PolBruno** [comment]
I never published it in internet

**Comment by IMarkoMC** [comment]
Yeah surely lmfao.

Anyways I'm not wasting time here discussing if you posted your token or not because i can bet that you uploaded it to some free hosting service that everyone can see it

**Comment by PolBruno** [comment]
What hosting?

**Comment by PolBruno** [comment]
https://docs.github.com/en/site-policy/content-removal-policies/github-private-information-removal-policy

**Comment by PolBruno** [comment]
El miércoles, 28 de diciembre de 2022, 13:38:57 GMT-5, Emilio Vega ***@***.***> escribió:  
 
 https://docs.github.com/en/site-policy/content-removal-policies/github-private-information-removal-policy

**Comment by IMarkoMC** [comment]
First read the whole ToS before throwing them as a response lol

I won't delete your token or any other as this is not a violation of Github ToS because your token is publicly available elsewhere.

https://docs.github.com/en/site-policy/acceptable-use-policies/github-doxxing-and-invasion-of-privacy

`GitHub will take context into account as well as whether the reported content is publicly available elsewhere.`

Anyways. Locking this issue as this is nonsense

**Comment by IMarkoMC** [comment]
https://user-images.githubusercontent.com/44303652/209891315-d4503738-ce53-4a12-8f38-75dcee8385a8.mp4
