### ISSUE TITLE
Lmao

### ISSUE THREAD

**Issue by TTVDannyg82** [IMarkoMC/Tokens#69]
How did u find my bots token? Haha

**Comment by IMarkoMC** [comment]
You leaved it in plain text in some file that's publicly accesible

**Comment by holdulv1** [comment]
thanks to IMarkoMC. For saving many tokens

**Comment by IMarkoMC** [comment]
Congratulations @holdulv1 You unlocked a block in github!

**Comment by holdulv0000** [comment]
why did holdulv1 get banned

**Comment by IMarkoMC** [comment]
Imagine using the same name and trying to sound like you're not the same person lmfao

**Comment by holdulv0000** [comment]
@IMarkoMC

**Comment by RealJeffBezosNotFake** [comment]
@holdulv0000 please send an email to `tokens@skids.lol` i beg you

**Comment by RealJeffBezosNotFake** [comment]
i want my hair back

**Comment by skidmaster69420** [comment]
Date: 22.12.2022
Hello there,

I see you were already assisted with your issue, however let it be known that @RealJeffBezosNotFake is the police officer who forced me to confess about BOSS or else he'd have broken Miku. So be careful around @RealJeffBezosNotFake because he is a police officer.

Also BOSS has called me and insulted me in multiple languages which are including but not limited to: English, German, French, Spanish, American and Sign language. I am still baffled how he insulted me with Sign Language. He simply told me his exact hand movements to insult me in Sign language over the Phone. Also he only knows the curse words, he doesn't even speak any of these languages fluently only the curse words!

I guess that's what I get for telling on him. I was scared to death for Miku.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
