### ISSUE TITLE
That's actually my radio bot, why is the bot token posted on GitHub?

### ISSUE THREAD

**Issue by emar** [IMarkoMC/Tokens#7]
Can you delete this post,
The code / token you're posting is from my Discord radio bot
I can prove it if I need to.

I created Psybient Sunset bot from a radio bot I found on Github
Discobot and this is the original creator https://github.com/leinstay/discobot

What I don't understand is why you would think it's ok to share someone else's Discord bot tokens on your Github,
That's surely against their policy right?
Especially when you could just as easily created a discord bot yourself and got tons of tokens..

**Comment by unknownsrc** [comment]
omg! not ur DISCORD RADIO BOT!

**Comment by BlackWolfWoof** [comment]
lmfao, they disabled your token by posting it to github since it was available on the internet for everyone to view. @emar 
Imagine if we didn't disable it or did something bad with it

**Comment by emar** [comment]
I'm lost, all I know is what Discord told me in an email,
About someone posting my bot token on Github.

**Comment by IMarkoMC** [comment]
Did you even read what @BlackWolfWoof said?

**Comment by Pabszito** [comment]
_smh my head_

**Comment by bchurton** [comment]
@emar The reason this was posted on Github was because you left your bot token public on Replit, and it was posted here before someone could do something malicious with it. Being posted here may have saved your bot!

**Comment by Pabszito** [comment]
Before you even complain again, read the official Replit documentation about how to use [secrets and environment varaibles](https://docs.replit.com/programming-ide/storing-sensitive-information-environment-variables)

**Comment by emar** [comment]
Ok fair enough, but I just received 4 more messages from Discord,
Someone posted 4 more tokens online, for my other radio bots.
I had created a team in my repl.it account... that's deleted now
Seems someone is accessing my repl

**Comment by IMarkoMC** [comment]
>  Seems someone is accessing my repl

You're leaving your tokens in plain text and everyone can see them
They'll be deleted sooner or later by my tools.

You should save your tokens in ENV variables

**Comment by emar** [comment]
Ok, I was just testing the DiscoBot code, if it'd work in Repl, and it does.
I'll have to redo his code to use Secrets..

**Comment by IMarkoMC** [comment]
>  I'll have to redo his code to use Secrets..

Change the part where the client connects to use ENV variables and not the config. The rest of the code will work

**Comment by emar** [comment]
Feck, there's always something,
It's like been hacked then told about it by Discord then fixing it on GitHub where it's posted

**Comment by IMarkoMC** [comment]
You only need to change the client.login(token) for client.login(process.env.TOKEN) and save the token as a env

**Comment by IMarkoMC** [comment]
> What I don't understand is why you would think it's ok to share someone else's Discord bot tokens on your Github,
> That's surely against their policy right?
> Especially when you could just as easily created a discord bot yourself and got tons of tokens..

Are you dumb or what m8

**Comment by IMarkoMC** [comment]
You didn't even read the fucking readme of this repo and you're accusing me of publishing your tokens. You're the one that left them in PLAIN TEXT
 
 You should be thankful that my tools found your token and i didn't straight up nuke your server but anyways if you're going that route I'm not wasting more time telling you how to do things.

**Comment by skidmaster69420** [comment]
Dear User,

You actually thought that deleting your messages will spare you the treatment of Skidmaster69420 LLC, because it would rob us of material to use against you? Oh how wrong you were, we have material for days, we have materials to feed our flies, we have material to fend of the debt collectors which have been coming by for our boss's massive debt which he got during betting. Which is why he only employs Unpaid Interns and Flies, which for some reason I need to pay. I find that unreasonable and quiet unreasonable. But he doesn't want to hear that, he wants to hear profit only. Meanwhile he's the only one in the company who can afford a Buggati Chiron, he keeps telling me "What color is your Buggati?!?!" I keep telling him "I am unpaid and you won't pay me." Then he slaps me 1000000 times for bringing up the topic of money. I tried bringing this up to the debt collectors, but they refuse to hear me out! Telling me "We ain't got no time for someone without a Buggati Chiron". I really need a Buggati to be heard in today's society. So please, help me reach my goal by supporting my gofundme.

GoFundMe: [https://www.gofundme.com/f/skidmaster69420-inter-buggati](https://cdn.discordapp.com/attachments/926099055887646791/1026295193797918871/unknown.png)

As you can see the flies are pretending to support me when in fact they paid me that 66 cents from my lunch money that they stole, my mom still is asking herself how I am not making any money at this company. It's been so long since I have seen my mom. 

Anyhow, you are not a top g.

Yours
Unpaid Intern
Skidmaster69420LLC
