### ISSUE TITLE
it well help a lot if you guys read this and make a reply #71

### ISSUE THREAD

**Issue by holdulv1** [IMarkoMC/Tokens#71]
hello there reader i do not hack but the guys that have stollen your token is a hacker 
i am sorry that whos read this have been hacked by someone in there life 
for more read this
https://github.com/IMarkoMC/Tokens/issues/70

**Comment by holdulv1** [comment]
you know this is public xd

**Comment by holdulv1** [comment]
i know you looking xd

**Comment by skidmaster69420** [comment]
Hi there,

Please refrain from making more then one issue and spamming replies, as you did in #70, as it scares the vultures. Our token hunting vultures are very temperamental and will shit in all of BOSS's 33 cars (including his Bugatti with w16 8.0L quad turbo) if scared. We have already lost a couple coworkers due to BOSS MANN's anger in this situation.

Respectfully,  
The Fly Department of Anti-Abuse
Skidmaster69420 LLC

**Comment by holdulv1** [comment]
skidmaster69420 what is this https://github.com/IMarkoMC/Tokens/pull/18 ha ha xd

**Comment by IMarkoMC** [comment]
https://user-images.githubusercontent.com/44303652/209976550-48b367c2-59dd-44b7-91d3-a7dd358dacab.mp4
