### ISSUE TITLE
You are a great person

### ISSUE THREAD

**Issue by Widenoname** [IMarkoMC/Tokens#74]
I don't know who you are but you are a great person and saved all of my work

**Comment by IMarkoMC** [comment]
Please use ENV variables to store your sensitive information going forward

**Comment by skidmaster69420** [comment]
Date: 26.12.2022

Hello there,

Thank you for thanking us so that we can thank you for thanking you for thanking us so that we can thank you. You are an awesome person! 

Also I realized that I did not share where I currently am. I am currently not in my 2x2 office, but in a very comfortable living arrangement which seems to be a random Jail cell in the federal prison. However they assured me I was under no criminal charges, that I was simply being kept in there for my own protection from the Hitmen. Because apparently BOSS hired 72 more Hitmen. 

He can pay that many Hitmen, but he can't pay me a decent living wage enough to cover my debt that I accumulated from being born and my therapy. Anyways, this prison is literal heaven. People don't constantly spit on me, hit me, use me as a basketball. It's very calm.

I love it here.

yours,
Unpaid Intern
SKIDMASTER69420 LLC.
