### ISSUE TITLE
Amazing, just amazing.

### ISSUE THREAD

**Issue by L3m0n-Cao** [IMarkoMC/Tokens#80]
I have many replit.com repos that mainly were used for rubbish stuff (I do random bots e.g from GitHub or that we made, and I strength test or mess around with friends).

This has helped me protect a hand full of servers with good conversations and photos I want to save and prevented them from gaining harm.

How does this work? do you scrape the internet? I'm kinda interested lol :)

btw, as I had like 3 bots, discord scared me 3 times and I thought I got warned, lmfao.

**Comment by skidmaster69420** [comment]
Hello there,

yeah it is a really weird thing. 

Also to give some Updates of me, as soon as Boss was arrested, I was let go from the Witness Program and sub sequentially released from the Federal Prison. I was then called by the Fly Department of Administration which told me that I was to work again but this time for a recent living wage. 

And that they would pay off all my debts. It seems at the end the company will be off just fine, if not even better than when Boss managed it. We are making profits for the first time since the War. It all turned out better than I had thought. I am very content with the 6x6 office room that was granted to me, much more comfortable than a measily 2x2 meter office room. But most importantly...

Miku is safe.

Yours,
Unpaid Intern
SKIDMASTER69420 LLC.
