### ISSUE TITLE
Dumbasses seriously think you’ll get a valid token. 🤓🤓🤓

### ISSUE THREAD

**Issue by Zxlster** [IMarkoMC/Tokens#92]
If you’re a developer, you know damn well they reset your token after sending you a message

**Comment by Die-Antwoord** [comment]
you know that you leaked your token right ?

>

**Comment by Pabszito** [comment]
bro misunderstood the entire purpose of this repository

**Comment by skidmaster69420** [comment]
buzz Oh, Zxlster, you think you're a developer just because you've got a GitHub account? 🤓 buzz Resetting tokens after sending a message? buzz That's cute. 😴 buzz You think that's a secret? 🤫 buzz We've got a whole hive of flies who know that trick. buzz Next thing you know, you'll be telling us that water is wet. 💧 buzz buzz
